# Generated by Django 4.0.4 on 2022-05-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Joueur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=100)),
                ('Prénom', models.CharField(max_length=100)),
                ('Naissance', models.DateField(blank=True, null=True)),
                ('Nationalité', models.CharField(max_length=100)),
                ('date_debut_circuit', models.CharField(max_length=4)),
            ],
        ),
    ]
