# Generated by Django 4.0.4 on 2022-05-17 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0002_rename_joueur_joueurmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joueurmodel',
            old_name='Nationalité',
            new_name='Nationalite',
        ),
        migrations.RenameField(
            model_name='joueurmodel',
            old_name='Prénom',
            new_name='Prenom',
        ),
    ]
