# Generated by Django 4.0.4 on 2022-05-18 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0003_rename_nationalité_joueurmodel_nationalite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pays', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='joueurmodel',
            name='Nationalite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliotheque.pays'),
        ),
    ]
