# Generated by Django 4.0.4 on 2022-05-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0004_pays_alter_joueurmodel_nationalite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joueurmodel',
            name='Nationalite',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Pays',
        ),
    ]
